name: Validate AI Tools Data

on:
  pull_request:
    paths:
      - 'data/**/*.json'
      - 'scripts/**'
  push:
    branches: [main]
    paths:
      - 'data/**/*.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run data validation
        run: npm run validate

      - name: Run tests
        run: npm run test

      - name: Format JSON files
        run: npm run format

      - name: Aggregate tools data
        run: npm run aggregate

  stats:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate stats
        run: npm run stats

      - name: Commit stats update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📊 Update database statistics"
          file_pattern: data/stats.json